name: Python CI

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Python Lint Code Scanning Action
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint

